import type { ContractListItem } from '../types/contract'

export const dashboardContracts: ContractListItem[] = [
  {
    id: 'contract-001',
    code: 'CTR-2026-0142',
    title: 'Apt Jardins 3q',
    property: 'Apt Jardins 3q',
    propertyAddress: 'Alameda Lorena, 1420',
    propertyId: 'apt-jardins-3q',
    propertyImageUrl:
      'https://images.unsplash.com/photo-1505693416388-ac5ce068fe85?auto=format&fit=crop&w=160&q=80',
    owner: 'Carlos Eduardo Mendes',
    tenant: 'Bruno Oliveira',
    status: 'Ativo',
    type: 'Residencial',
    startDate: '01/09/2026',
    endDate: '30/08/2027',
    amount: 'R$ 6.500',
    adjustment: 'IGPM anual',
    paymentDay: '5 de cada mes',
    guarantee: 'Fiador',
    notes:
      'O locatario compromete-se a entregar o imovel nas mesmas condicoes de conservacao em que o recebeu. Eventuais reformas estruturais dependem de aprovacao previa expressa por escrito do locador.',
    paymentHistory: [
      { period: 'Junho 2026', amount: 'R$ 6.500', status: 'Pago', date: '05/06' },
      { period: 'Maio 2026', amount: 'R$ 6.500', status: 'Pago', date: '05/05' },
      { period: 'Abril 2026', amount: 'R$ 6.500', status: 'Pago', date: '05/04' },
      { period: 'Marco 2026', amount: 'R$ 6.500', status: 'Pago', date: '05/03' },
      { period: 'Fevereiro 2026', amount: 'R$ 6.500', status: 'Pago', date: '05/02' },
      { period: 'Janeiro 2026', amount: 'R$ 6.500', status: 'Pendente', date: '--' },
    ],
    documents: [
      { name: 'Contrato_Assinado_Jardins.pdf', sentAt: 'Enviado em 01/09/2026' },
      { name: 'Laudo_Vistoria_Entrada.pdf', sentAt: 'Enviado em 28/08/2026' },
      { name: 'Documentos_Locatario_Bruno.pdf', sentAt: 'Enviado em 20/08/2026' },
    ],
    updatedAt: 'Hoje',
  },
  {
    id: 'contract-002',
    code: 'CTR-2026-0141',
    title: 'Studio Pinheiros',
    property: 'Studio Pinheiros',
    propertyAddress: 'Rua Teodoro Sampaio, 840',
    propertyId: 'studio-pinheiros',
    propertyImageUrl:
      'https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?auto=format&fit=crop&w=160&q=80',
    owner: 'Marina Costa',
    tenant: 'Mariana Costa',
    status: 'Ativo',
    type: 'Residencial',
    startDate: '10/11/2023',
    endDate: '10/11/2026',
    amount: 'R$ 3.200',
    adjustment: 'IPCA anual',
    paymentDay: '10 de cada mes',
    guarantee: 'Seguro fianca',
    notes:
      'Contrato residencial com vistoria inicial anexada e acompanhamento mensal dos repasses ao proprietario.',
    paymentHistory: [
      { period: 'Agosto 2026', amount: 'R$ 3.200', status: 'Pago', date: '10/08' },
      { period: 'Julho 2026', amount: 'R$ 3.200', status: 'Pago', date: '10/07' },
      { period: 'Junho 2026', amount: 'R$ 3.200', status: 'Pago', date: '10/06' },
      { period: 'Maio 2026', amount: 'R$ 3.200', status: 'Pago', date: '10/05' },
    ],
    documents: [
      { name: 'Contrato_Studio_Pinheiros.pdf', sentAt: 'Enviado em 10/11/2023' },
      { name: 'Seguro_Fianca_Mariana.pdf', sentAt: 'Enviado em 08/11/2023' },
    ],
    updatedAt: 'Ontem',
  },
  {
    id: 'contract-003',
    code: 'CTR-2026-0138',
    title: 'Cobertura Itaim',
    property: 'Cobertura Itaim',
    propertyAddress: 'Rua Tabapuã, 1100',
    propertyId: 'cobertura-itaim',
    propertyImageUrl:
      'https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?auto=format&fit=crop&w=160&q=80',
    owner: 'Helena Prado',
    tenant: 'Tech Soluções Ltda',
    status: 'Em revisão',
    type: 'Residencial',
    startDate: '15/03/2024',
    endDate: '15/03/2027',
    amount: 'R$ 4.500.000',
    adjustment: 'Sem reajuste',
    paymentDay: 'A combinar',
    guarantee: 'Sinal contratual',
    notes: 'Minuta em revisao para formalizacao de venda com validacao documental pendente.',
    paymentHistory: [{ period: 'Sinal', amount: 'R$ 450.000', status: 'Pendente', date: '--' }],
    documents: [
      { name: 'Minuta_Cobertura_Itaim.pdf', sentAt: 'Enviado em 24/08/2026' },
      { name: 'Matricula_Atualizada.pdf', sentAt: 'Enviado em 22/08/2026' },
    ],
    updatedAt: '2 dias',
  },
  {
    id: 'contract-004',
    code: 'CTR-2026-0132',
    title: 'Casa Alto de Pinheiros',
    property: 'Casa Alto de Pinheiros',
    propertyAddress: 'Rua Cerro Corá, 450',
    propertyId: 'casa-alto-pinheiros',
    propertyImageUrl:
      'https://images.unsplash.com/photo-1600566753190-17f0baa2a6c3?auto=format&fit=crop&w=160&q=80',
    owner: 'Paulo Mendes',
    tenant: 'Carlos Eduardo',
    status: 'Aguardando assinatura',
    type: 'Residencial',
    startDate: '05/05/2022',
    endDate: '05/05/2027',
    amount: 'R$ 3.800.000',
    adjustment: 'Sem reajuste',
    paymentDay: 'A combinar',
    guarantee: 'Sinal contratual',
    notes: 'Contrato aguardando assinatura das partes e validacao final do financeiro.',
    paymentHistory: [
      { period: 'Sinal', amount: 'R$ 380.000', status: 'Pago', date: '05/05' },
      { period: 'Saldo', amount: 'R$ 3.420.000', status: 'Pendente', date: '--' },
    ],
    documents: [{ name: 'Contrato_Casa_Alto_Pinheiros.pdf', sentAt: 'Enviado em 05/05/2026' }],
    updatedAt: '5 dias',
  },
  {
    id: 'contract-005',
    code: 'CTR-2026-0125',
    title: 'Studio Bela Vista',
    property: 'Studio Bela Vista',
    propertyAddress: 'Avenida Nove de Julho, 2100',
    propertyId: 'studio-bela-vista',
    propertyImageUrl:
      'https://images.unsplash.com/photo-1505693416388-ac5ce068fe85?auto=format&fit=crop&w=160&q=80',
    owner: 'Renata Ferraz',
    tenant: 'Juliana Mendes',
    status: 'Encerrado',
    type: 'Residencial',
    startDate: '01/01/2025',
    endDate: '01/01/2026',
    amount: 'R$ 2.400',
    adjustment: 'IGPM anual',
    paymentDay: '1 de cada mes',
    guarantee: 'Caucao',
    notes: 'Contrato encerrado com vistoria de saida concluida e sem pendencias financeiras.',
    paymentHistory: [
      { period: 'Janeiro 2026', amount: 'R$ 2.400', status: 'Pago', date: '01/01' },
      { period: 'Dezembro 2025', amount: 'R$ 2.400', status: 'Pago', date: '01/12' },
    ],
    documents: [
      { name: 'Termo_Encerramento_Studio_Bela_Vista.pdf', sentAt: 'Enviado em 02/01/2026' },
    ],
    updatedAt: '1 semana',
  },
  {
    id: 'contract-006',
    code: 'CTR-2026-0118',
    title: 'Apt Moema 2q',
    property: 'Apt Moema 2q',
    propertyAddress: 'Alameda dos Maracatins, 320',
    propertyId: 'apt-moema-2q',
    propertyImageUrl:
      'https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?auto=format&fit=crop&w=160&q=80',
    owner: 'Vila Nova Prime',
    tenant: 'Ana Silva',
    status: 'Ativo',
    type: 'Residencial',
    startDate: '01/02/2024',
    endDate: '01/02/2027',
    amount: 'R$ 4.800',
    adjustment: 'IPCA anual',
    paymentDay: '5 de cada mes',
    guarantee: 'Fiador',
    notes:
      'Locacao ativa com pagamento recorrente e garantia por fiador. Reajuste anual previsto no aniversario do contrato.',
    paymentHistory: [
      { period: 'Junho 2026', amount: 'R$ 4.800', status: 'Pago', date: '05/06' },
      { period: 'Maio 2026', amount: 'R$ 4.800', status: 'Pago', date: '05/05' },
      { period: 'Abril 2026', amount: 'R$ 4.800', status: 'Pago', date: '05/04' },
      { period: 'Marco 2026', amount: 'R$ 4.800', status: 'Pago', date: '05/03' },
      { period: 'Fevereiro 2026', amount: 'R$ 4.800', status: 'Pago', date: '05/02' },
      { period: 'Janeiro 2026', amount: 'R$ 4.800', status: 'Pendente', date: '--' },
    ],
    documents: [
      { name: 'Contrato_Assinado_Moema.pdf', sentAt: 'Enviado em 01/02/2024' },
      { name: 'Laudo_Vistoria_Entrada.pdf', sentAt: 'Enviado em 28/01/2024' },
      { name: 'Documentos_Locatario_Ana.pdf', sentAt: 'Enviado em 22/01/2024' },
    ],
    updatedAt: '2 semanas',
  },
]

export function getDashboardContractById(contractId: string) {
  return dashboardContracts.find((contract) => contract.id === contractId) ?? null
}
