import '@testing-library/jest-dom/vitest'
import { cleanup } from '@testing-library/react'
import { afterEach, vi } from 'vitest'

vi.mock('next-intl', () => ({
  useLocale: () => 'pt-BR',
  useTranslations: (namespace?: string) => {
    const messages: Record<string, string | ((values: Record<string, unknown>) => string)> = {
      'auth.login.email.label': 'E-mail',
      'auth.login.email.placeholder': 'seu@email.com',
      'auth.login.forgotPassword': 'Esqueceu a senha?',
      'auth.login.google.ariaLabel': 'Continuar com Google (em breve)',
      'auth.login.google.label': 'Continuar com Google',
      'auth.login.password.hide': 'Ocultar senha',
      'auth.login.password.label': 'Senha',
      'auth.login.password.show': 'Mostrar senha',
      'auth.login.prompt.createAccount': 'Criar conta',
      'auth.login.prompt.question': 'Não tem conta?',
      'auth.login.separator': 'ou',
      'auth.login.submit': 'Entrar',
      'auth.login.subtitle': 'Acesse sua conta para gerenciar imóveis',
      'auth.login.title': 'Entrar na sua conta',
      'auth.passwordRecovery.backToLogin': 'Voltar ao login',
      'auth.passwordRecovery.brandDescription':
        'Recupere o acesso à sua carteira de imóveis e clientes',
      'auth.passwordRecovery.confirmation.description':
        'Verifique sua caixa de entrada e siga as instruções para redefinir sua senha.',
      'auth.passwordRecovery.confirmation.mobileDescription':
        'Enviamos as instruções para o seu e-mail.',
      'auth.passwordRecovery.confirmation.title': 'E-mail enviado!',
      'auth.passwordRecovery.email.label': 'E-mail',
      'auth.passwordRecovery.email.placeholder': 'seu@email.com',
      'auth.passwordRecovery.resend': 'Reenviar e-mail',
      'auth.passwordRecovery.resendCountdown': ({ time }) => `Reenviar em ${time}`,
      'auth.passwordRecovery.submit': 'Enviar instruções',
      'auth.passwordRecovery.subtitle': 'Digite seu e-mail para redefinir sua senha',
      'auth.passwordRecovery.successBrandDescription':
        'Enviamos um link de recuperação para seu e-mail cadastrado',
      'auth.passwordRecovery.title': 'Recuperar senha',
      'auth.register.benefits.dashboardResults': 'Acompanhe resultados em um dashboard completo',
      'auth.register.benefits.propertyManagement': 'Gerencie seus imóveis de forma inteligente',
      'auth.register.benefits.qualifiedClients': 'Conecte-se com clientes qualificados',
      'auth.register.copyright': '© 2026 Ketris. Todos os direitos reservados.',
      'auth.register.profileStep.ariaLabel': 'Perfil',
      'auth.register.profileStep.continue': 'Continuar',
      'auth.register.profileStep.subtitle': 'Escolha como você vai usar o Ketris',
      'auth.register.profileStep.title': 'Qual é o seu perfil?',
      'auth.register.profiles.construtora.description': 'Lance empreendimentos e gerencie vendas',
      'auth.register.profiles.construtora.title': 'Construtora',
      'auth.register.profiles.corretor.description':
        'Conecte-se a proprietários e feche mais negócios',
      'auth.register.profiles.corretor.title': 'Corretor',
      'auth.register.profiles.imobiliaria.description':
        'Gerencie sua carteira e equipe de corretores',
      'auth.register.profiles.imobiliaria.title': 'Imobiliária',
      'auth.register.profiles.locatario.description': 'Encontre o imóvel ideal para morar',
      'auth.register.profiles.locatario.title': 'Locatário',
      'auth.register.profiles.proprietario.description':
        'Gerencie seus imóveis e encontre inquilinos',
      'auth.register.profiles.proprietario.title': 'Proprietário',
      'auth.register.progress.label': ({ currentStep, totalSteps }) =>
        `Etapa ${currentStep} de ${totalSteps}`,
      'auth.register.progress.shortLabel': ({ currentStep, totalSteps }) =>
        `Passo ${currentStep} de ${totalSteps}`,
      'auth.registerDetails.creci.label': 'CRECI',
      'auth.registerDetails.creci.optionalHelper': 'Campo opcional para este perfil',
      'auth.registerDetails.creci.placeholder': '00000-F',
      'auth.registerDetails.creci.requiredHelper': 'Campo obrigatório para corretores',
      'auth.registerDetails.email.label': 'E-mail',
      'auth.registerDetails.email.placeholder': 'seu@email.com',
      'auth.registerDetails.fullName.label': 'Nome completo',
      'auth.registerDetails.fullName.placeholder': 'Digite seu nome completo',
      'auth.registerDetails.password.label': 'Senha',
      'auth.registerDetails.password.placeholder': 'Crie uma senha',
      'auth.registerDetails.passwordConfirmation.label': 'Confirmar senha',
      'auth.registerDetails.passwordConfirmation.placeholder': 'Confirme a senha',
      'auth.registerDetails.passwordVisibility.hide': ({ field }) => `Ocultar ${field}`,
      'auth.registerDetails.passwordVisibility.show': ({ field }) => `Mostrar ${field}`,
      'auth.registerDetails.phone.label': 'Telefone',
      'auth.registerDetails.phone.placeholder': '(11) 99999-9999',
      'auth.registerDetails.submit': 'Criar conta',
      'auth.registerDetails.terms.connector': 'e',
      'auth.registerDetails.terms.prefix': 'Li e aceito os',
      'auth.registerDetails.terms.privacyPolicy': 'Política de Privacidade',
      'auth.registerDetails.terms.termsOfUse': 'Termos de Uso',
      'marketplace.header.announceProperty': 'Anunciar Imóvel',
      'marketplace.header.closeMenu': 'Fechar menu',
      'marketplace.header.mainMenu': 'Menu principal',
      'marketplace.header.notifications': 'notificações',
      'marketplace.header.openMenu': 'Abrir menu',
      'marketplace.header.openProfile': 'Abrir perfil',
      'marketplace.navigation.agencies': 'Imobiliárias',
      'marketplace.navigation.brokers': 'Corretores',
      'marketplace.navigation.buy': 'Comprar',
      'marketplace.navigation.home': 'Início',
      'marketplace.navigation.rent': 'Alugar',
      'marketplace.home.featured.title': 'Imóveis em destaque',
      'marketplace.home.featured.viewAll': 'Ver todos os imóveis',
      'marketplace.home.hero.subtitle':
        'Aluguel e venda de imóveis com tecnologia de ponta, processos ágeis e total confiança.',
      'marketplace.home.hero.stats.activeProperties': 'imóveis ativos',
      'marketplace.home.hero.stats.partnerBrokers': 'corretores parceiros',
      'marketplace.home.hero.stats.servedCities': 'cidades atendidas',
      'marketplace.home.hero.titleLine1': 'A infraestrutura digital',
      'marketplace.home.hero.titleLine2': 'do mercado imobiliário',
      'marketplace.home.hero.brandAnimation': 'Animação da marca Ketris',
      'marketplace.home.miniProperties.eyebrow':
        '+2.500 imóveis qualificados e verificados digitalmente',
      'marketplace.home.search.apply': 'Aplicar',
      'marketplace.home.search.clearSearch': 'Limpar busca',
      'marketplace.home.search.closePriceRange': 'Fechar faixa de preço',
      'marketplace.home.search.filters.location': 'Localização',
      'marketplace.home.search.filters.priceRange': 'Faixa de preço',
      'marketplace.home.search.filters.propertyType': 'Tipo de imóvel',
      'marketplace.home.search.locationPlaceholder': 'Digite cidade ou bairro',
      'marketplace.home.search.maxPrice': 'Máximo',
      'marketplace.home.search.minPrice': 'Mínimo',
      'marketplace.home.search.mobilePlaceholder': 'Buscar por bairro, cidade...',
      'marketplace.home.search.noResults': 'Nenhum resultado',
      'marketplace.home.search.priceRange': 'Faixa de preço',
      'marketplace.home.search.propertyTypes.apartment': 'Apartamento',
      'marketplace.home.search.propertyTypes.commercialRooms': 'Salas comerciais',
      'marketplace.home.search.propertyTypes.farms': 'Chácaras e sítios',
      'marketplace.home.search.propertyTypes.landLots': 'Terrenos e lotes',
      'marketplace.home.search.propertyTypes.penthouses': 'Coberturas',
      'marketplace.home.search.propertyTypes.residentialHouses': 'Casas residenciais',
      'marketplace.home.search.propertyTypes.studios': 'Studios',
      'marketplace.home.search.propertyTypePlaceholder': 'Digite o tipo de imóvel',
      'marketplace.home.search.submit': 'Buscar',
      'marketplace.footer.description':
        'Tecnologia e simplificação de ponta a ponta no mercado imobiliário corporativo e residencial.',
      'marketplace.footer.rights': 'Tecnologias Ltda. Todos os direitos reservados.',
      'marketplace.profile.actions.settings': 'Configurações',
      'marketplace.profile.actions.signOut': 'Sair',
      'marketplace.profile.actions.support': 'Suporte',
      'marketplace.profile.actions.switchMode': 'Trocar modalidade',
      'marketplace.profile.closeProfile': 'Fechar perfil',
      'marketplace.profile.dialogLabel': 'Perfil do usuário',
      'marketplace.profile.language': 'Idioma',
      'marketplace.profile.languages.en': 'Inglês',
      'marketplace.profile.languages.es': 'Espanhol',
      'marketplace.profile.languages.ptBR': 'Português',
      'marketplace.profile.role': 'Corretor parceiro',
      'marketplace.publicProfile.listings.title': 'Imóveis representados',
      'marketplace.publicProfile.listings.featured': 'DESTAQUE',
      'marketplace.publicProfile.listings.featuredTitle': 'Imóveis em destaque',
      'marketplace.publicProfile.listings.viewAriaLabel': ({ title }) => `Ver imóvel ${title}`,
      'marketplace.publicProfile.listings.viewProperty': 'Ver imóvel',
      'marketplace.publicProfile.metrics.active': 'Ativos',
      'marketplace.publicProfile.metrics.closed': 'Fechados',
      'marketplace.publicProfile.metrics.properties': 'Imóveis',
      'marketplace.publicProfile.metrics.rating': 'Nota',
      'marketplace.publicProfile.metrics.responseTime': 'Tempo médio',
      'marketplace.publicProfile.metrics.team': 'Equipe',
      'marketplace.publicProfile.metrics.years': 'Anos',
      'marketplace.publicProfile.propertyCard.new': 'Novo',
      'marketplace.publicProfile.propertyCard.viewDetails': 'Ver detalhes',
      'marketplace.propertyDetail.gallery.closeGallery': 'Fechar galeria',
      'marketplace.propertyDetail.gallery.hiddenPhotos': ({ count }) =>
        `+${count} ${Number(count) === 1 ? 'foto' : 'fotos'}`,
      'marketplace.propertyDetail.gallery.nextPhoto': 'Próxima foto',
      'marketplace.propertyDetail.gallery.openGallery': 'Abrir galeria de fotos do imóvel',
      'marketplace.propertyDetail.gallery.openPhoto': ({ index, total }) =>
        `Abrir foto ${index} de ${total}`,
      'marketplace.propertyDetail.gallery.photoAlt': ({ title, index }) =>
        `${title} - foto ${index}`,
      'marketplace.propertyDetail.gallery.photoCounter': ({ current, total }) =>
        `${current} de ${total}`,
      'marketplace.propertyDetail.gallery.previousPhoto': 'Foto anterior',
      'marketplace.propertyDetail.gallery.selectPhoto': ({ index }) => `Ver foto ${index}`,
      'marketplace.propertyDetail.gallery.viewPhotos': 'Ver fotos',
      'marketplace.directory.cards.activeProperties': ({ count }) => `${count} ativos`,
      'marketplace.directory.cards.properties': 'Imóveis',
      'marketplace.directory.cards.rating': 'Nota',
      'marketplace.directory.cards.region': 'Região',
      'marketplace.directory.cards.response': 'Resposta',
      'marketplace.directory.cards.team': 'Equipe',
      'marketplace.directory.cards.viewPublicPage': 'Ver página pública',
      'marketplace.directory.cards.viewPublicPageAriaLabel': ({ name }) =>
        `Ver página pública de ${name}`,
      'marketplace.profileEditor.addMember': 'Adicionar membro',
      'marketplace.profileEditor.appearance': 'Aparência',
      'marketplace.profileEditor.bannerPreview': 'Prévia do banner',
      'marketplace.profileEditor.configurableProfile': 'Perfil público configurável',
      'marketplace.profileEditor.contactActions.call': 'Ligar',
      'marketplace.profileEditor.contactActions.email': 'E-mail',
      'marketplace.profileEditor.contactActions.openPublicLink': 'Abrir link público',
      'marketplace.profileEditor.dropImage': 'Solte a imagem aqui',
      'marketplace.profileEditor.dropToMove': 'Solte para mover',
      'marketplace.profileEditor.emptyMembers': 'Nenhum membro adicionado.',
      'marketplace.profileEditor.fields.accentColor': 'Cor de destaque',
      'marketplace.profileEditor.fields.backgroundColor': 'Fundo do perfil',
      'marketplace.profileEditor.fields.bannerUrl': 'URL do banner',
      'marketplace.profileEditor.fields.displayName': 'Nome exibido',
      'marketplace.profileEditor.fields.headline': 'Chamada do banner',
      'marketplace.profileEditor.fields.name': 'Nome',
      'marketplace.profileEditor.fields.photoUrl': 'URL da foto',
      'marketplace.profileEditor.fields.primaryColor': 'Cor principal',
      'marketplace.profileEditor.fields.profileUrl': 'Link do perfil',
      'marketplace.profileEditor.fields.role': 'Função',
      'marketplace.profileEditor.fields.summary': 'Resumo',
      'marketplace.profileEditor.fields.uploadBanner': 'Enviar banner',
      'marketplace.profileEditor.fields.uploadPhoto': 'Enviar foto de perfil',
      'marketplace.profileEditor.images': 'Imagens',
      'marketplace.profileEditor.mainContent': 'Conteúdo principal',
      'marketplace.profileEditor.memberTitle': ({ index }) => `Membro ${index}`,
      'marketplace.profileEditor.newMember': 'Novo membro',
      'marketplace.profileEditor.photoPreview': 'Prévia da foto',
      'marketplace.profileEditor.positionLabel': ({ position, label }) =>
        `Posição ${position}: ${label}`,
      'marketplace.profileEditor.position': ({ position }) => `Posição ${position}`,
      'marketplace.profileEditor.preparing': 'Preparando...',
      'marketplace.profileEditor.previewDialog.close': 'Fechar visualização',
      'marketplace.profileEditor.previewDialog.title': 'Visualização do perfil',
      'marketplace.profileEditor.preview': 'Visualizar',
      'marketplace.profileEditor.profileOrder': 'Ordem do perfil',
      'marketplace.profileEditor.removeMember': 'Remover',
      'marketplace.profileEditor.saveDraft': 'Salvar rascunho',
      'marketplace.profileEditor.sections.contact.description':
        'Link público, telefone, e-mail e dados rápidos.',
      'marketplace.profileEditor.sections.contact.label': 'Contato',
      'marketplace.profileEditor.sections.hero.description':
        'Banner, foto, nome e chamada principal.',
      'marketplace.profileEditor.sections.hero.label': 'Apresentação',
      'marketplace.profileEditor.sections.listings.description': 'Cards de imóveis representados.',
      'marketplace.profileEditor.sections.listings.label': 'Imóveis',
      'marketplace.profileEditor.sections.metrics.description':
        'Nota, tempo médio, ativos e negociações.',
      'marketplace.profileEditor.sections.metrics.label': 'Indicadores',
      'marketplace.profileEditor.sections.none.description': 'Não exibir seção nesta posição.',
      'marketplace.profileEditor.sections.none.label': 'Nenhum',
      'marketplace.profileEditor.sections.team.description':
        'Corretores ou pessoas destacadas no perfil.',
      'marketplace.profileEditor.sections.team.label': 'Equipe',
      'marketplace.profileEditor.subtitle':
        'Ajuste aparência, imagens e ordem das seções exibidas para visitantes.',
      'marketplace.profileEditor.team': 'Equipe',
      'marketplace.profileEditor.teamDescription':
        'Adicione membros destacados e o link para cada perfil público.',
      'marketplace.profileEditor.title': 'Editar Perfil',
      'marketplace.profileEditor.uploadHelper':
        'JPG, PNG ou WEBP. Você também pode manter apenas o link acima.',
      'marketplace.profileEditor.validatedDraft': 'Rascunho validado',
      'marketplace.agencyProfileEditor.appearance': 'Aparência',
      'marketplace.agencyProfileEditor.bannerPreview': 'Prévia do banner',
      'marketplace.agencyProfileEditor.brandImages': 'Imagens da marca',
      'marketplace.agencyProfileEditor.contactActions.call': 'Ligar',
      'marketplace.agencyProfileEditor.contactActions.email': 'E-mail',
      'marketplace.agencyProfileEditor.contactActions.openPublicLink': 'Abrir link público',
      'marketplace.agencyProfileEditor.dropImage': 'Solte a imagem aqui',
      'marketplace.agencyProfileEditor.dropToMove': 'Solte para mover',
      'marketplace.agencyProfileEditor.fields.accentColor': 'Cor de destaque',
      'marketplace.agencyProfileEditor.fields.address': 'Endereço',
      'marketplace.agencyProfileEditor.fields.backgroundColor': 'Fundo da marca',
      'marketplace.agencyProfileEditor.fields.bannerUrl': 'URL do banner',
      'marketplace.agencyProfileEditor.fields.coverage': 'Cobertura',
      'marketplace.agencyProfileEditor.fields.displayName': 'Nome da imobiliária',
      'marketplace.agencyProfileEditor.fields.headline': 'Chamada institucional',
      'marketplace.agencyProfileEditor.fields.headquarters': 'Sede',
      'marketplace.agencyProfileEditor.fields.legalCreci': 'CRECI',
      'marketplace.agencyProfileEditor.fields.logoUrl': 'URL do logo',
      'marketplace.agencyProfileEditor.fields.primaryColor': 'Cor principal',
      'marketplace.agencyProfileEditor.fields.segments': 'Segmentos',
      'marketplace.agencyProfileEditor.fields.summary': 'Resumo',
      'marketplace.agencyProfileEditor.fields.uploadBanner': 'Enviar banner',
      'marketplace.agencyProfileEditor.fields.uploadLogo': 'Enviar logo',
      'marketplace.agencyProfileEditor.logoPreview': 'Prévia do logo',
      'marketplace.agencyProfileEditor.mainContent': 'Conteúdo principal',
      'marketplace.agencyProfileEditor.metrics.properties': 'Imóveis',
      'marketplace.agencyProfileEditor.metrics.rating': 'Nota',
      'marketplace.agencyProfileEditor.metrics.team': 'Equipe',
      'marketplace.agencyProfileEditor.metrics.years': 'Anos',
      'marketplace.agencyProfileEditor.positionLabel': ({ position, label }) =>
        `Posição ${position}: ${label}`,
      'marketplace.agencyProfileEditor.position': ({ position }) => `Posição ${position}`,
      'marketplace.agencyProfileEditor.preparing': 'Preparando...',
      'marketplace.agencyProfileEditor.previewDialog.close': 'Fechar visualização',
      'marketplace.agencyProfileEditor.previewDialog.title':
        'Visualização do perfil da imobiliária',
      'marketplace.agencyProfileEditor.preview': 'Visualizar',
      'marketplace.agencyProfileEditor.profileOrder': 'Ordem do perfil',
      'marketplace.agencyProfileEditor.saveDraft': 'Salvar rascunho',
      'marketplace.agencyProfileEditor.sections.brand.description':
        'Logo, banner, nome e chamada institucional.',
      'marketplace.agencyProfileEditor.sections.brand.label': 'Marca',
      'marketplace.agencyProfileEditor.sections.contact.description':
        'Link público, telefone, e-mail e dados rápidos.',
      'marketplace.agencyProfileEditor.sections.contact.label': 'Contato',
      'marketplace.agencyProfileEditor.sections.listings.description':
        'Cards de imóveis representados.',
      'marketplace.agencyProfileEditor.sections.listings.label': 'Imóveis',
      'marketplace.agencyProfileEditor.sections.metrics.description':
        'Imóveis, equipe, anos de mercado e nota.',
      'marketplace.agencyProfileEditor.sections.metrics.label': 'Indicadores',
      'marketplace.agencyProfileEditor.sections.none.description':
        'Não exibir seção nesta posição.',
      'marketplace.agencyProfileEditor.sections.none.label': 'Nenhum',
      'marketplace.agencyProfileEditor.sections.team.description':
        'Corretores em destaque na imobiliária.',
      'marketplace.agencyProfileEditor.sections.team.label': 'Equipe',
      'marketplace.agencyProfileEditor.subtitle':
        'Ajuste marca, imagens e ordem das seções exibidas para visitantes.',
      'marketplace.agencyProfileEditor.title': 'Editar Perfil da Imobiliária',
      'marketplace.agencyProfileEditor.uploadHelper':
        'JPG, PNG ou WEBP. Você também pode manter apenas o link acima.',
      'marketplace.agencyProfileEditor.validatedDraft': 'Rascunho validado',
      'crm.contacts.actions.editContact': ({ name }) => `Editar ${name}`,
      'crm.contacts.actions.moreOptions': ({ name }) => `Mais opções para ${name}`,
      'crm.contacts.actions.viewInteractions': ({ name }) => `Ver interações de ${name}`,
      'crm.contacts.empty': 'Nenhum contato encontrado.',
      'crm.contacts.filterAriaLabel': 'Filtrar contatos por tipo',
      'crm.contacts.filters.all': 'Todos',
      'crm.contacts.filters.brokers': 'Corretores',
      'crm.contacts.filters.owners': 'Proprietários',
      'crm.contacts.filters.tenants': 'Locatários',
      'crm.contacts.mobileListAriaLabel': 'Lista móvel de contatos',
      'crm.contacts.newContact': 'Novo Contato',
      'crm.contacts.pagination.next': 'Próximo',
      'crm.contacts.pagination.previous': 'Anterior',
      'crm.contacts.propertyCount': ({ count }) => `${count} imóveis`,
      'crm.contacts.resultsRange': ({ first, last, total }) =>
        `Mostrando ${first}–${last} de ${total}`,
      'crm.contacts.searchAriaLabel': 'Buscar contatos',
      'crm.contacts.searchPlaceholder': 'Buscar contato por nome, email, fone...',
      'crm.contacts.selectAllVisible': 'Selecionar todos os contatos visíveis',
      'crm.contacts.selectContact': ({ name }) => `Selecionar ${name}`,
      'crm.contacts.tableAriaLabel': 'Contatos do CRM',
      'crm.contacts.tableColumns.actions': 'Ações',
      'crm.contacts.tableColumns.email': 'Email',
      'crm.contacts.tableColumns.lastInteraction': 'Última interação',
      'crm.contacts.tableColumns.name': 'Nome',
      'crm.contacts.tableColumns.phone': 'Telefone',
      'crm.contacts.tableColumns.properties': 'Imóveis',
      'crm.contacts.tableColumns.type': 'Tipo',
      'crm.contacts.title': 'Contatos',
      'crm.contacts.types.broker': 'Corretor',
      'crm.contacts.types.owner': 'Proprietário',
      'crm.contacts.types.tenant': 'Locatário',
      'crm.access.loadingSession': 'Carregando sessão',
      'crm.access.restrictedDescription':
        'Entre com uma conta vinculada a um tenant para visualizar as oportunidades.',
      'crm.access.restrictedTitle': 'Acesso restrito ao CRM',
      'crm.access.signIn': 'Entrar no Ketris',
      'crm.navigation.openNavigation': 'Abrir navegação',
      'crm.pipeline.allStages': 'Todas as etapas',
      'crm.pipeline.boardAriaLabel': 'Pipeline de oportunidades',
      'crm.pipeline.dataLoadError': 'Não foi possível carregar os dados do pipeline.',
      'crm.pipeline.emptyStage': 'Nenhuma oportunidade nesta etapa.',
      'crm.pipeline.filterByStage': 'Filtrar por etapa',
      'crm.pipeline.loadError': 'Não foi possível carregar as oportunidades.',
      'crm.pipeline.newOpportunity': 'Nova Oportunidade',
      'crm.pipeline.newOpportunityDisabledAriaLabel':
        'Nova Oportunidade: fluxo de criação em preparação',
      'crm.pipeline.newOpportunityTooltip': 'Fluxo de criação em preparação',
      'crm.pipeline.openOpportunityAriaLabel': ({ name }) => `Abrir oportunidade de ${name}`,
      'crm.pipeline.projectedTotal': 'Total projetado',
      'crm.pipeline.projectedTotalAriaLabel': ({ stage }) => `Total projetado de ${stage}`,
      'crm.pipeline.propertyUnavailable': 'Imóvel indisponível no catálogo',
      'crm.pipeline.retry': 'Tentar novamente',
      'crm.pipeline.searchAriaLabel': 'Buscar oportunidade',
      'crm.pipeline.searchPlaceholder': 'Buscar oportunidade...',
      'crm.pipeline.stages.accepted': 'Fechado',
      'crm.pipeline.stages.closed': 'Fechado',
      'crm.pipeline.stages.draft': 'Prospecção',
      'crm.pipeline.stages.negotiation': 'Negociação',
      'crm.pipeline.stages.proposal': 'Proposta',
      'crm.pipeline.stages.prospecting': 'Prospecção',
      'crm.pipeline.stages.qualification': 'Qualificação',
      'crm.pipeline.stages.rejected': 'Perdido',
      'crm.pipeline.stages.sent': 'Proposta enviada',
      'crm.pipeline.title': 'Pipeline de Vendas',
      'crm.pipeline.totalLabels.rent': 'Aluguel',
      'crm.pipeline.totalLabels.sale': 'Venda',
      'crm.pipeline.totalLabels.uncategorized': 'Sem categoria',
      'crm.opportunityDetail.archive': 'Arquivar oportunidade',
      'crm.opportunityDetail.archiveDescription':
        'A oportunidade deixará de aparecer no pipeline ativo, mas continuará armazenada no CRM.',
      'crm.opportunityDetail.archiveError': 'Não foi possível arquivar a oportunidade.',
      'crm.opportunityDetail.archiveSuccess': 'Oportunidade arquivada.',
      'crm.opportunityDetail.archiveTitle': 'Arquivar oportunidade?',
      'crm.opportunityDetail.backToPipeline': 'Voltar ao pipeline',
      'crm.opportunityDetail.breadcrumbAriaLabel': 'Navegação estrutural',
      'crm.opportunityDetail.confirmStageDescription': ({ from, name, to }) =>
        `Mover ${name} de ${from} para ${to}?`,
      'crm.opportunityDetail.confirmStageTitle': 'Confirmar mudança de etapa',
      'crm.opportunityDetail.contactInterestTitle': 'Informações de contato e interesse',
      'crm.opportunityDetail.createdActivityDetail': 'Registro incluído no pipeline.',
      'crm.opportunityDetail.createdActivityTitle': 'Oportunidade criada',
      'crm.opportunityDetail.editTitle': 'Editar oportunidade',
      'crm.opportunityDetail.fields.contractTerm': 'Prazo do contrato (meses)',
      'crm.opportunityDetail.fields.contractTermLabel': 'Prazo de contrato',
      'crm.opportunityDetail.fields.email': 'E-mail',
      'crm.opportunityDetail.fields.guarantee': 'Garantia',
      'crm.opportunityDetail.fields.intendedStart': 'Início pretendido',
      'crm.opportunityDetail.fields.months': ({ count }) => `${count} meses`,
      'crm.opportunityDetail.fields.name': 'Nome',
      'crm.opportunityDetail.fields.notes': 'Observações',
      'crm.opportunityDetail.fields.notInformed': 'Não informado',
      'crm.opportunityDetail.fields.phone': 'Telefone',
      'crm.opportunityDetail.fields.proposedValue': 'Valor proposto',
      'crm.opportunityDetail.fields.specialConditions': 'Condições especiais',
      'crm.opportunityDetail.fields.specialConditionsHelper': 'Separe as condições por vírgulas.',
      'crm.opportunityDetail.guarantees.CAUCAO': 'Caução',
      'crm.opportunityDetail.guarantees.FIADOR': 'Fiador',
      'crm.opportunityDetail.guarantees.NENHUMA': 'Não informada',
      'crm.opportunityDetail.guarantees.SEGURO_FIANCA': 'Seguro-fiança',
      'crm.opportunityDetail.loadError': 'Não foi possível carregar esta oportunidade.',
      'crm.opportunityDetail.movedSuccess': ({ stage }) => `Oportunidade movida para ${stage}.`,
      'crm.opportunityDetail.pipelineLink': 'Pipeline',
      'crm.opportunityDetail.propertyPanel.loadError': ({ id }) =>
        `Não foi possível carregar o imóvel associado. Referência: ${id}`,
      'crm.opportunityDetail.propertyPanel.monthlySuffix': '/mês',
      'crm.opportunityDetail.propertyPanel.retry': 'Tentar novamente',
      'crm.opportunityDetail.propertyPanel.title': 'Imóvel associado',
      'crm.opportunityDetail.updateError': 'Não foi possível atualizar a oportunidade.',
      'crm.opportunityDetail.updateStageError': 'Não foi possível atualizar a etapa.',
      'crm.opportunityDetail.updateSuccess': 'Oportunidade atualizada.',
      'crm.opportunityDetail.updatedActivityDetail': ({ stage }) => `Etapa atual: ${stage}.`,
      'crm.opportunityDetail.updatedActivityTitle': 'Oportunidade atualizada',
      'crm.opportunityDetail.unknownLocation': 'Localização não informada',
      'crm.opportunityDetail.actions.cancel': 'Cancelar',
      'crm.opportunityDetail.actions.confirmStageChange': 'Confirmar mudança',
      'crm.opportunityDetail.actions.saveChanges': 'Salvar alterações',
      'marketplace.searchResults.filters.allRegions': 'Todas as regiões',
      'marketplace.searchResults.filters.area': 'Área',
      'marketplace.searchResults.filters.bedrooms': 'Quartos',
      'marketplace.searchResults.filters.button': 'Filtros',
      'marketplace.searchResults.filters.buttonWithCount': ({ count }) => `Filtros (${count})`,
      'marketplace.searchResults.filters.clear': 'Limpar',
      'marketplace.searchResults.filters.clearSearch': 'Limpar busca',
      'marketplace.searchResults.filters.close': 'Fechar filtros',
      'marketplace.searchResults.filters.done': 'Concluir',
      'marketplace.searchResults.filters.maxPrice': 'Preço máximo',
      'marketplace.searchResults.filters.minArea': 'Área mínima',
      'marketplace.searchResults.filters.onlyWithParking': 'Somente imóveis com vaga',
      'marketplace.searchResults.filters.options.100m²+': '100m²+',
      'marketplace.searchResults.filters.options.2+ quartos': '2+ quartos',
      'marketplace.searchResults.filters.options.3+ quartos': '3+ quartos',
      'marketplace.searchResults.filters.options.90m²+': '90m²+',
      'marketplace.searchResults.filters.options.Apartamento': 'Apartamento',
      'marketplace.searchResults.filters.options.Casa': 'Casa',
      'marketplace.searchResults.filters.options.Cobertura': 'Cobertura',
      'marketplace.searchResults.filters.options.Com vaga': 'Com vaga',
      'marketplace.searchResults.filters.options.Loft': 'Loft',
      'marketplace.searchResults.filters.options.Preço': 'Preço',
      'marketplace.searchResults.filters.options.Quartos': 'Quartos',
      'marketplace.searchResults.filters.options.Todos': 'Todos',
      'marketplace.searchResults.filters.options.Todos os tipos': 'Todos os tipos',
      'marketplace.searchResults.filters.options.Até R$ 10.000': 'Até R$ 10.000',
      'marketplace.searchResults.filters.options.Até R$ 6.000': 'Até R$ 6.000',
      'marketplace.searchResults.filters.options.Área': 'Área',
      'marketplace.searchResults.filters.price': 'Preço',
      'marketplace.searchResults.filters.title': 'Filtros',
      'marketplace.searchResults.filters.type': 'Tipo',
    }

    return (key: string, values: Record<string, unknown> = {}) => {
      const message = messages[namespace ? `${namespace}.${key}` : key]

      if (typeof message === 'function') return message(values)

      return message ?? key
    }
  },
}))

vi.mock('@/i18n/navigation', async () => {
  const React = await import('react')

  function formatHref(
    href:
      | string
      | { pathname: string; params?: Record<string, string>; query?: Record<string, string> },
  ) {
    if (typeof href === 'string') return href

    const pathname = href.params
      ? Object.entries(href.params).reduce(
          (currentPathname, [key, value]) => currentPathname.replace(`[${key}]`, value),
          href.pathname,
        )
      : href.pathname
    const localizedPathname = pathname
      .replace(/^\/properties(?=\/|$)/, '/imoveis')
      .replace(/^\/brokers(?=\/|$)/, '/corretores')
      .replace(/^\/agencies(?=\/|$)/, '/imobiliarias')
    const query = href.query ? new URLSearchParams(href.query).toString() : ''

    return query ? `${localizedPathname}?${query}` : localizedPathname
  }

  return {
    usePathname: () => '/',
    useRouter: () => ({
      back: vi.fn(),
      forward: vi.fn(),
      prefetch: vi.fn(),
      push: vi.fn(),
      refresh: vi.fn(),
      replace: vi.fn(),
    }),
    Link: React.forwardRef<HTMLAnchorElement, React.AnchorHTMLAttributes<HTMLAnchorElement>>(
      function MockLocalizedLink({ href = '', ...props }, ref) {
        return React.createElement('a', { ...props, href: formatHref(href), ref })
      },
    ),
  }
})

afterEach(() => {
  cleanup()
})
